import { LegalShell } from "@/components/LegalShell";
import { LEGAL } from "@/lib/legal";
export const metadata = { title: "Politique de confidentialité" };
export default function PrivacyPage() { return <LegalShell titleFr="Politique de confidentialité" titleEn="Privacy policy" childrenFr={<Privacy/>} childrenEn={<Privacy english/>}/>; }
function Privacy({english=false}:{english?:boolean}) {
  const t=(fr:string,en:string)=>english?en:fr;
  return <div><h2>1. {t("Responsable du traitement", "Controller")}</h2><p>{LEGAL.tradeName} — {LEGAL.proprietor}, {LEGAL.address}. <a href={`mailto:${LEGAL.email}`}>{LEGAL.email}</a>.</p>
    <h2>2. {t("Données et finalités", "Data and purposes")}</h2><p>{t("Nous traitons votre nom, email, mot de passe haché, sessions, confirmations email, paramètres, présentation du business, recherches publiques enregistrées, médias, recettes de carrousels et calendrier pour exécuter le service demandé. Les références de paiement, droits d’accès et preuves de consentement servent à la facturation et aux obligations légales. Les compteurs de quotas, erreurs techniques et journaux d’exploitation servent à la sécurité et à la fiabilité sur la base de notre intérêt légitime.", "We process names, emails, password hashes, sessions, email confirmations, settings, business profiles, saved public research, media, carousel recipes and schedules to perform the requested service. Payment references, entitlements and consent evidence support billing and legal obligations. Quota counters, technical errors and operational logs support security and reliability based on our legitimate interests.")}</p>
    <h2 id="tiktok">3. TikTok, Google et MCP</h2><p>{t("TikTok est connecté uniquement sur autorisation OAuth. Selon les scopes approuvés, nous traitons identifiants, profil, métriques, liste des posts et jetons d’accès/renouvellement conservés côté serveur. Nous ne collectons pas votre mot de passe TikTok. Les lectures et publications exécutent vos demandes, y compris vos programmations. Google peut fournir identité et email confirmé. Vos clés MCP donnent accès à votre espace : les données demandées par l’assistant sont transmises au client IA que vous choisissez, soumis à sa propre politique.", "TikTok connects only through OAuth authorization. Approved scopes may provide identifiers, profile data, metrics, posts and server-side access/refresh tokens. We do not collect TikTok passwords. Reads and publications execute your requests, including scheduled posts. Google may provide identity and verified email. MCP keys grant workspace access: assistant-requested data is sent to your chosen AI client under its own privacy policy.")}</p>
    <h2>4. {t("Prestataires", "Providers")}</h2><p>{t("Vercel héberge le service et les médias privés ; PostgreSQL/Neon héberge les données lorsque configuré. Stripe traite les paiements, Resend les emails transactionnels, Brave les requêtes de découverte et un prestataire technique les métadonnées TikTok publiques. Aucun numéro complet de carte n’est stocké par ScrollShow. Nous ne vendons pas vos données. Certains prestataires peuvent traiter des données hors EEE ; leurs garanties contractuelles et mécanismes de transfert doivent être maintenus par PROCESS.", "Vercel hosts the service and private media; PostgreSQL/Neon hosts data when configured. Stripe processes payments, Resend transactional emails, Brave discovery queries and a technical provider public TikTok metadata. ScrollShow does not store full card numbers or sell your data. Providers may process data outside the EEA; PROCESS must maintain appropriate contractual safeguards and transfer mechanisms.")}</p>
    <h2>5. {t("Conservation et suppression", "Retention and deletion")}</h2><p>{t("Les données actives sont conservées pour fournir le compte. La suppression retire les références utilisateur après résolution des publications en cours, de la facturation et de la déconnexion des services. Les médias devenus sans référence sont mis en file de suppression après 48 heures ; un média encore utilisé par un autre post est conservé. Les liens de médias signés expirent au plus tard après 24 heures. Les sauvegardes chiffrées du store sont conservées 30 jours selon la politique d’exploitation ; les éléments soumis à une obligation comptable sont conservés pour la durée légale applicable. Les incidents de suppression sont suivis et peuvent nécessiter une intervention du support.", "Active data is retained to provide the account. Account deletion removes user references after resolving in-flight publications, billing and service disconnections. Unreferenced media is queued for deletion after 48 hours; media still referenced by a post is retained. Signed media links expire within 24 hours. Encrypted store backups are retained for 30 days under the operational policy; legally required accounting records remain for the applicable statutory period. Deletion failures are tracked and may require support intervention.")}</p>
    <h2>6. {t("Vos droits", "Your rights")}</h2><p>{t("Vous pouvez demander accès, rectification, effacement, limitation, opposition et portabilité, selon les conditions du RGPD. Un export est disponible dans les réglages. Contactez PROCESS ; une vérification proportionnée de votre identité peut être nécessaire. Vous pouvez introduire une réclamation auprès de la CNIL. Le refus de fournir les informations nécessaires au contrat empêche l’accès aux fonctions correspondantes.", "You may request access, correction, erasure, restriction, objection and portability under GDPR conditions. Settings provide an export. Contact PROCESS; proportionate identity verification may be required. You may lodge a complaint with the CNIL. Without information necessary for the contract, corresponding features cannot be provided.")} <a href="https://www.cnil.fr/fr/adresser-une-plainte">CNIL</a>.</p>
    <h2>7. {t("Cookies et sécurité", "Cookies and security")}</h2><p>{t("Le cookie de session HTTP-only et les stockages de préférences servent à la connexion et à l’interface. Les outils d’analyse ou de publicité non nécessaires ne doivent pas être activés sans le consentement requis. Aucun suivi GPS n’est réalisé. Les clés doivent rester privées ; révoquez-les depuis les réglages si elles sont compromises.", "The HTTP-only session cookie and preference storage support login and the interface. Non-essential analytics or advertising must not be enabled without required consent. No GPS tracking is performed. Keep API keys private and revoke compromised keys through settings.")}</p>
    <h2 id="commerce">8. {t("Revenus et suivi des contenus", "Revenue and content measurement")}</h2>
    <p>{t("Lorsque vous connectez Stripe, RevenueCat ou Shopify à un projet, ScrollShow traite les identifiants techniques du compte, des clients, des commandes et des transactions, leurs dates, montants, devises, états et remboursements pour fournir les résultats demandés et les relier aux contenus suivis. Le connecteur Shopify ne demande pas les noms, adresses, emails ni numéros de téléphone des clients. Il utilise un accès en lecture aux commandes et ne modifie ni produits, ni commandes, ni remboursements. Les identifiants d’accès et de renouvellement restent chiffrés côté serveur.", "When you connect Stripe, RevenueCat or Shopify to a project, ScrollShow processes technical account, customer, order and transaction identifiers, dates, amounts, currencies, statuses and refunds to provide the requested reports and associate them with tracked content. The Shopify connector does not request customer names, addresses, emails or phone numbers. It reads orders and does not change products, orders or refunds. Access and refresh credentials remain encrypted on the server.")}</p>
    <p>{t("Les liens suivis utilisent une référence aléatoire de clic. Le redirecteur ne conserve pas l’adresse IP du visiteur. Le script de suivi ne place pas de cookie et n’utilise pas de stockage local par défaut. Une conservation locale du clic pendant sept jours peut être activée par le site du business après le consentement approprié du visiteur. Le business choisit les événements transmis par son serveur, informe ses visiteurs et applique leurs choix. Une vente sans origine observée reste non attribuée.", "Tracked links use a random click reference. The redirect service does not retain the visitor's IP address. The tracking script sets no cookie and uses no local storage by default. The business website can enable seven-day local click retention after obtaining appropriate visitor consent. The business chooses which events its server sends, informs visitors and applies their choices. Sales without an observed source remain unattributed.")}</p>
    <p>{t("Les données restent limitées au projet autorisé. Les journaux de ventes et de remboursements sont exportables depuis Résultats. Déconnecter une source retire ses identifiants locaux et conserve l’historique déjà collecté ; supprimer le compte efface ses données business. Les demandes Shopify d’accès ou d’effacement des données sont traitées dans le périmètre de la boutique concernée. Les sauvegardes chiffrées suivent la rétention de 30 jours décrite ci-dessus. Pour exercer un droit sur des données traitées pour une boutique, contactez d’abord cette boutique ou notre contact de confidentialité.", "Data remains limited to the authorized project. Sales and refund ledgers can be exported from Results. Disconnecting a source removes its local credentials and retains previously collected history; account deletion removes its business data. Shopify data access and erasure requests are handled within the relevant shop's scope. Encrypted backups follow the 30-day retention described above. For rights concerning data processed for a shop, contact that shop first or our privacy contact.")}</p>
    <h2 id="extension">9. {t("Extension Chrome ScrollShow", "ScrollShow Chrome extension")}</h2>
    <p>{t("L’extension est facultative. Elle n’agit que lorsque vous lancez une recherche depuis ScrollShow : elle ouvre la recherche TikTok dans votre propre navigateur, lit les résultats publics que TikTok vous affiche (carrousels, légendes, compteurs, identifiant public du compte auteur) et les transmet à votre compte ScrollShow, où ils rejoignent votre historique de recherche.", "The extension is optional. It only acts when you start a search from ScrollShow: it opens the TikTok search in your own browser, reads the public results TikTok displays to you (carousels, captions, counters, the author’s public handle) and sends them to your ScrollShow account, where they join your search history.", )}</p>
    <p>{t("Elle ne lit ni vos messages, ni vos identifiants, ni vos cookies TikTok, ni votre historique de navigation, et n’est active sur aucune autre page. Aucune donnée n’est vendue ni transmise à un tiers. Les demandes de connexion ou de vérification de TikTok ne sont jamais contournées. Désinstaller l’extension met fin à tout traitement ; les résultats déjà enregistrés se suppriment depuis ScrollShow.", "It does not read your messages, credentials, TikTok cookies or browsing history, and is not active on any other page. No data is sold or shared with third parties. TikTok login or verification prompts are never bypassed. Uninstalling the extension ends all processing; results already saved can be deleted from ScrollShow.")}</p>
  </div>;
}
