import { LegalShell } from "@/components/LegalShell";
import { LEGAL } from "@/lib/legal";
export const metadata = { title: "Politique de confidentialité" };
export default function PrivacyPage() { return <LegalShell titleFr="Politique de confidentialité" titleEn="Privacy policy" childrenFr={<Privacy/>} childrenEn={<Privacy english/>}/>; }
function Privacy({english=false}:{english?:boolean}) {
  const t=(fr:string,en:string)=>english?en:fr;
  return <div><h2>1. {t("Responsable du traitement", "Controller")}</h2><p>{LEGAL.tradeName} — {LEGAL.proprietor}, {LEGAL.address}. <a href={`mailto:${LEGAL.email}`}>{LEGAL.email}</a>.</p>
    <h2>2. {t("Données et finalités", "Data and purposes")}</h2><p>{t("Nous traitons votre nom, email, mot de passe haché, sessions, confirmations email, paramètres, présentation du business, recherches publiques enregistrées, médias, recettes de carrousels et calendrier pour exécuter le service demandé. Les références de paiement, droits d’accès et preuves de consentement servent à la facturation et aux obligations légales. Les compteurs de quotas, erreurs techniques et journaux d’exploitation servent à la sécurité et à la fiabilité sur la base de notre intérêt légitime.", "We process names, emails, password hashes, sessions, email confirmations, settings, business profiles, saved public research, media, carousel recipes and schedules to perform the requested service. Payment references, entitlements and consent evidence support billing and legal obligations. Quota counters, technical errors and operational logs support security and reliability based on our legitimate interests.")}</p>
    <h2 id="tiktok">3. TikTok, Google et MCP</h2><p>{t("TikTok est connecté uniquement sur autorisation OAuth. Selon les scopes approuvés, nous traitons identifiants, profil, métriques, liste des posts et jetons d’accès/renouvellement conservés côté serveur. Nous ne collectons pas votre mot de passe TikTok. Les lectures et publications exécutent vos demandes, y compris vos programmations. Google peut fournir identité et email confirmé. Vos clés MCP donnent accès à votre espace : les données demandées par l’assistant sont transmises au client IA que vous choisissez, soumis à sa propre politique.", "TikTok connects only through OAuth authorization. Approved scopes may provide identifiers, profile data, metrics, posts and server-side access/refresh tokens. We do not collect TikTok passwords. Reads and publications execute your requests, including scheduled posts. Google may provide identity and verified email. MCP keys grant workspace access: assistant-requested data is sent to your chosen AI client under its own privacy policy.")}</p>
    <h2>4. {t("Prestataires", "Providers")}</h2><p>{t("Vercel héberge le service et les médias privés ; PostgreSQL/Neon héberge les données lorsque configuré. Stripe traite les paiements, Resend les emails transactionnels, Brave les requêtes de découverte et Monid les métadonnées TikTok publiques. Aucun numéro complet de carte n’est stocké par ScrollShow. Nous ne vendons pas vos données. Certains prestataires peuvent traiter des données hors EEE ; leurs garanties contractuelles et mécanismes de transfert doivent être maintenus par PROCESS.", "Vercel hosts the service and private media; PostgreSQL/Neon hosts data when configured. Stripe processes payments, Resend transactional emails, Brave discovery queries and Monid public TikTok metadata. ScrollShow does not store full card numbers or sell your data. Providers may process data outside the EEA; PROCESS must maintain appropriate contractual safeguards and transfer mechanisms.")}</p>
    <h2>5. {t("Conservation et suppression", "Retention and deletion")}</h2><p>{t("Les données actives sont conservées pour fournir le compte. La suppression retire les références utilisateur après résolution des publications en cours, de la facturation et de la déconnexion des services. Les médias devenus sans référence sont mis en file de suppression après 48 heures ; un média encore utilisé par un autre post est conservé. Les liens de médias signés expirent au plus tard après 24 heures. Les sauvegardes chiffrées du store sont conservées 30 jours selon la politique d’exploitation ; les éléments soumis à une obligation comptable sont conservés pour la durée légale applicable. Les incidents de suppression sont suivis et peuvent nécessiter une intervention du support.", "Active data is retained to provide the account. Account deletion removes user references after resolving in-flight publications, billing and service disconnections. Unreferenced media is queued for deletion after 48 hours; media still referenced by a post is retained. Signed media links expire within 24 hours. Encrypted store backups are retained for 30 days under the operational policy; legally required accounting records remain for the applicable statutory period. Deletion failures are tracked and may require support intervention.")}</p>
    <h2>6. {t("Vos droits", "Your rights")}</h2><p>{t("Vous pouvez demander accès, rectification, effacement, limitation, opposition et portabilité, selon les conditions du RGPD. Un export est disponible dans les réglages. Contactez PROCESS ; une vérification proportionnée de votre identité peut être nécessaire. Vous pouvez introduire une réclamation auprès de la CNIL. Le refus de fournir les informations nécessaires au contrat empêche l’accès aux fonctions correspondantes.", "You may request access, correction, erasure, restriction, objection and portability under GDPR conditions. Settings provide an export. Contact PROCESS; proportionate identity verification may be required. You may lodge a complaint with the CNIL. Without information necessary for the contract, corresponding features cannot be provided.")} <a href="https://www.cnil.fr/fr/adresser-une-plainte">CNIL</a>.</p>
    <h2>7. {t("Cookies et sécurité", "Cookies and security")}</h2><p>{t("Le cookie de session HTTP-only et les stockages de préférences servent à la connexion et à l’interface. Les outils d’analyse ou de publicité non nécessaires ne doivent pas être activés sans le consentement requis. Aucun suivi GPS n’est réalisé. Les clés doivent rester privées ; révoquez-les depuis les réglages si elles sont compromises.", "The HTTP-only session cookie and preference storage support login and the interface. Non-essential analytics or advertising must not be enabled without required consent. No GPS tracking is performed. Keep API keys private and revoke compromised keys through settings.")}</p>
  </div>;
}
