/** Deliberately accepts no credentials or profile data: context comes from authenticated tools. */
export function scrollshowStarterPrompt(english = false): string {
  return english ? `Use the connected ScrollShow SaaS MCP tools to prepare my first original TikTok photo carousel for my business.

1. Call whoami, then get_content_brief. Read my business profile, available capabilities, saved research and calendar. Ask only for essential missing information; do not ask me to repeat my onboarding.
2. Inspect list_posts before creating anything to avoid duplicate posts. Suggest relevant hooks (three is a starting point, adapt to my request), distinguish measured evidence from creative hypotheses, and choose one with a short explanation. If no research is available, say so and work from my business profile without inventing accounts or metrics.
3. Prepare a complete carousel using create_post: readable slides with editable text overlays in recipe, an original hook, useful content, a clear CTA and a caption. Five slides is a starting point, not a limit. Inspect the recipe and preview when available. Use only assets I have rights to use; do not copy a competitor's carousel.
4. Place the finished carousel in the calendar. Read whoami.calendar for timezone, current date and default time; reuse my editorial plan and avoid occupied slots. create_post includes it in the calendar; for a completed fork or import, use set_calendar with inCalendar=true. Reuse my scheduling authorization and publication choices without asking again. When the channel, date/time and TikTok choices are known, use status="scheduled" to enable publication at that time. Otherwise save the complete carousel with a proposed date and status="draft", explain exactly what is missing and ask only for that information. Do not share publicly or delete anything without my explicit request.
5. Confirm saving only after a successful tool response, including inCalendar=true. Return the actual ID, slide outline, calendar link, date/time/timezone and whether publication is scheduled or a choice is still missing. If a write fails or times out, inspect existing posts before retrying.

If ScrollShow tools are unavailable, inspect the existing connection and follow the skill's setup instructions. Reuse a valid authorization and continue as soon as the tools are available; do not ask for a confirmation word or a routine restart. A chat message does not install the connector by itself. If authentication or access is refused, act on the actual error without simulating results. Never ask me to paste an API key into this conversation.` : `Utilise les outils MCP du SaaS ScrollShow connecté pour préparer mon premier carrousel photo TikTok original pour mon activité.

1. Appelle whoami, puis get_content_brief. Lis mon profil d’entreprise, les capacités disponibles, les recherches enregistrées et mon calendrier. Demande uniquement les informations indispensables manquantes, sans me refaire l’onboarding.
2. Consulte list_posts avant toute création pour éviter les doublons. Propose des accroches pertinentes (trois est un point de départ, adapte-toi à ma demande), distingue les observations mesurées des hypothèses créatives, puis choisis-en une avec une courte explication. Sans recherches disponibles, signale-le et pars de mon profil sans inventer de comptes ni de statistiques.
3. Prépare un carrousel complet avec create_post : des slides lisibles et des textes éditables dans recipe, une accroche originale, du contenu utile, un appel à l’action clair et une légende. Cinq slides est un point de départ, pas une limite. Vérifie la recette et l’aperçu disponible. Utilise seulement des visuels dont j’ai les droits, sans copier le carrousel d’un concurrent.
4. Mets le carrousel terminé dans le calendrier. Lis whoami.calendar pour le fuseau, la date actuelle et l’heure habituelle ; réutilise mon plan éditorial et évite les créneaux occupés. create_post l’inclut dans le calendrier ; pour une duplication ou un import finalisé, utilise set_calendar avec inCalendar=true. Réutilise mon autorisation de programmation et mes choix de publication sans me les redemander. Quand le compte, la date/heure et les options TikTok sont connus, utilise status="scheduled" pour activer la publication à cette heure. Sinon, enregistre le carrousel complet avec une date proposée et status="draft", indique précisément ce qui manque et demande uniquement cette information. Ne partage publiquement et ne supprime rien sans ma demande explicite.
5. Confirme l’enregistrement uniquement après une réponse réussie de l’outil, avec inCalendar=true. Donne l’identifiant réel, le plan des slides, le lien du calendrier, la date/heure et le fuseau, et précise si la publication est programmée ou si un choix manque encore. Si l’écriture échoue ou expire, consulte les posts existants avant de réessayer.

Si les outils ScrollShow sont absents, vérifie la connexion existante et suis les instructions d’installation de la skill. Réutilise une autorisation valide et poursuis dès que les outils sont disponibles, sans exiger un mot de confirmation ni un redémarrage systématique. Un message ne suffit pas à installer le connecteur à lui seul. Si l’authentification ou l’accès est refusé, traite l’erreur réelle sans simuler de résultats. Ne me demande jamais de coller une clé API dans cette conversation.`;
}
