export const PLATFORMS = [
  { id: "x", name: "X", color: "#000" },
  { id: "linkedin", name: "LinkedIn", color: "#0a66c2" },
  { id: "linkedin-page", name: "LinkedIn Page", color: "#0a66c2" },
  { id: "reddit", name: "Reddit", color: "#ff4500" },
  { id: "instagram-fb", name: "Instagram (Facebook Business)", color: "#e4405f" },
  { id: "instagram", name: "Instagram (Standalone)", color: "#e4405f" },
  { id: "facebook", name: "Facebook Page", color: "#1877f2" },
  { id: "threads", name: "Threads", color: "#000" },
  { id: "youtube", name: "YouTube", color: "#ff0000" },
  { id: "gmb", name: "Google My Business", color: "#4285f4" },
  { id: "tiktok", name: "TikTok", color: "#111" },
  { id: "pinterest", name: "Pinterest", color: "#e60023" },
  { id: "dribbble", name: "Dribbble", color: "#ea4c89" },
  { id: "discord", name: "Discord", color: "#5865f2" },
  { id: "slack", name: "Slack", color: "#611f69" },
  { id: "kick", name: "Kick", color: "#53fc18" },
  { id: "twitch", name: "Twitch", color: "#9146ff" },
  { id: "mastodon", name: "Mastodon", color: "#6364ff" },
  { id: "bluesky", name: "Bluesky", color: "#1185fe" },
  { id: "lemmy", name: "Lemmy", color: "#1485d0" },
  { id: "farcaster", name: "Farcaster", color: "#8a63d2" },
  { id: "telegram", name: "Telegram", color: "#26a5e4" },
  { id: "nostr", name: "Nostr", color: "#8b5cf6" },
  { id: "vk", name: "VK", color: "#0077ff" },
  { id: "medium", name: "Medium", color: "#000" },
  { id: "devto", name: "Dev.to", color: "#0a0a0a" },
  { id: "hashnode", name: "Hashnode", color: "#2962ff" },
  { id: "wordpress", name: "WordPress", color: "#21759b" },
  { id: "listmonk", name: "ListMonk", color: "#0055d4" },
  { id: "moltbook", name: "Moltbook", color: "#111" },
  { id: "whop", name: "Whop", color: "#f97316" },
  { id: "skool", name: "Skool", color: "#facc15" },
  { id: "mewe", name: "MeWe", color: "#007a5a" },
  { id: "tumblr", name: "Tumblr", color: "#36465d" },
] as const;

export function platformName(id: string) {
  return PLATFORMS.find((item) => item.id === id)?.name || id;
}
