"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useStudio } from "./StudioContext";
import type { Account } from "@/lib/types";
import type { researchMetrics } from "@/lib/research/statistics";
import type { publicJob } from "@/lib/research/jobs";
import type { getStudy } from "@/lib/research/formats";
import type { FormatStudy } from "@/lib/research/model";
import "./research.css";

type Item={account:Account;metrics:ReturnType<typeof researchMetrics>;measuredAt:string|null};
type Job=ReturnType<typeof publicJob>;
type Study=Awaited<ReturnType<typeof getStudy>>;
async function api(url:string,body?:unknown){const r=await fetch(url,body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:undefined);const j=await r.json();if(!r.ok)throw new Error(j.error||"request_failed");return j;}
export function ResearchView(){
  const {english}=useStudio();const tr=(fr:string,en:string)=>english?en:fr;
  const [items,setItems]=useState<Item[]>([]),[jobs,setJobs]=useState<Job[]>([]),[studies,setStudies]=useState<FormatStudy[]>([]);
  const [tab,setTab]=useState("library"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [kind,setKind]=useState("discover"),[source,setSource]=useState("provider"),[query,setQuery]=useState(""),[filter,setFilter]=useState(""),[sort,setSort]=useState("median");
  const [days,setDays]=useState(30),[target,setTarget]=useState(10),[minViews,setMinViews]=useState(100000),[minMedian,setMinMedian]=useState(0),[minShare,setMinShare]=useState(50),[minPosts,setMinPosts]=useState(5),[maxPages,setMaxPages]=useState(3),[pivot,setPivot]=useState(false);
  const [available,setAvailable]=useState(false),[selectedJob,setSelectedJob]=useState<string|null>(null),[study,setStudy]=useState<Study|null>(null),[studying,setStudying]=useState(false);
  const load=useCallback(async()=>{try{const [r,j,s]=await Promise.all([api(`/api/research?days=${days}`),api("/api/research/jobs"),api("/api/research/studies")]);setItems(r.items);setAvailable(r.discoveryAvailable);setJobs(j.jobs);setStudies(s.studies);}catch(e){setError(e instanceof Error?e.message:"load_failed");}finally{setLoading(false);}},[days]);
  useEffect(()=>{void load();},[load]);
  const active=jobs.some(j=>["queued","running"].includes(j.status));
  useEffect(()=>{if(!active)return;let pending=false;const timer=setInterval(()=>{if(pending)return;pending=true;void load().finally(()=>{pending=false;});},5000);return()=>clearInterval(timer);},[active,load]);
  useEffect(()=>{if(!active)return;const timer=setInterval(()=>{const queued=jobs.find(j=>j.status==="queued"&&j.input.source==="provider");if(queued)void api(`/api/research/jobs/${queued.id}`,{action:"advance"}).catch(()=>{});},12000);return()=>clearInterval(timer);},[active,jobs]);
  const num=(n:number|null|undefined)=>n==null?"—":Math.round(n).toLocaleString(english?"en-US":"fr-FR");
  const percent=(n:number|null|undefined)=>n==null?"—":`${Math.round(n*100)} %`;
  const status=(s:string)=>({queued:tr("En attente","Queued"),running:tr("Collecte en cours","Collecting"),done:tr("Terminée","Done"),paused:tr("En pause","Paused"),needs_attention:tr("Intervention requise","Needs attention"),stopped:tr("Arrêtée","Stopped"),error:tr("Erreur","Error")}[s]||s);
  const reason=(s:string)=>({no_posts_in_window:tr("Aucun post dans la période","No posts in period"),insufficient_slideshows:tr("Pas assez de carrousels mesurés","Too few measured carousels"),slideshow_share_below_filter:tr("Part de carrousels trop faible","Slideshow share below filter"),median_views_below_filter:tr("Médiane sous le seuil","Median below threshold"),total_views_below_filter:tr("Total de vues sous le seuil","Total views below threshold"),followers_below_filter:tr("Abonnés sous le seuil","Followers below threshold"),followers_unavailable:tr("Abonnés non mesurés","Followers unavailable")}[s]||s);
  async function start(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const j=await api("/api/research/jobs",{kind,source,keywords:query.split(/[,\n]/).map(x=>x.trim()).filter(Boolean),target,maxPages,hashtagPivot:pivot,filters:{days,minSlideshowShare:minShare/100,minMedianViews:minMedian,minTotalViews:minViews,minPosts},requestId:crypto.randomUUID()});setSelectedJob(j.id);setTab("runs");await load();}catch(e){setError(e instanceof Error?e.message:"research_failed");}finally{setBusy(false);}}
  async function control(id:string,action:string,retune=false){try{await api(`/api/research/jobs/${id}`,{action,...retune?{filters:{days,minSlideshowShare:minShare/100,minMedianViews:minMedian,minTotalViews:minViews,minPosts}}:{}});await load();}catch(e){setError(e instanceof Error?e.message:"research_failed");}}
  async function openStudy(accountId:string,postId:string){setStudying(true);setError("");try{setStudy(await api("/api/research/studies",{accountId,postId}));setTab("formats");await load();}catch(e){setError(e instanceof Error?e.message:"study_failed");}finally{setStudying(false);}}
  async function continueStudy(){if(!study)return;setStudying(true);try{setStudy(await api(`/api/research/studies/${study.id}`,{}));await load();}catch(e){setError(e instanceof Error?e.message:"study_failed");}finally{setStudying(false);}}
  const visible=useMemo(()=>items.filter(i=>`${i.account.handle} ${i.account.bio||""} ${i.account.niche} ${i.account.notes}`.toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>sort==="followers"?b.account.followers-a.account.followers:sort==="ratio"?(b.metrics.medianViewsPerFollower??-1)-(a.metrics.medianViewsPerFollower??-1):(b.metrics.medianViews??-1)-(a.metrics.medianViews??-1)),[items,filter,sort]);
  const selected=jobs.find(j=>j.id===selectedJob);
  return <div className="ss-research">
    <section className="ss-panel ss-research-intro"><span className="ss-research-eyebrow">{tr("RECHERCHE · FORMATS · PREUVES","RESEARCH · FORMATS · EVIDENCE")}</span><h2>{tr("Comprendre ce qui mérite d’être reproduit","Understand what is worth repeating")}</h2><p className="ss-lead">{tr("Découvre les comptes de ta niche, mesure leurs carrousels et étudie leurs formats slide par slide. Ton assistant transforme ces preuves en idées originales pour ton activité.","Discover niche accounts, measure photo posts and study their formats slide by slide. Your assistant turns this evidence into original ideas for your business.")}</p>
    <form onSubmit={start}>
      <div className="ss-research__form"><label>{tr("Recherche","Research")}<select className="ss-input" value={kind} onChange={e=>setKind(e.target.value)}><option value="discover">{tr("Découvrir des comptes","Discover accounts")}</option><option value="analyze">{tr("Analyser des comptes","Analyze accounts")}</option></select></label>
      <label className="ss-research-query">{kind==="discover"?tr("Mots-clés séparés par des virgules","Comma-separated keywords"):tr("Comptes séparés par des virgules","Comma-separated accounts")}<input className="ss-input" required minLength={2} maxLength={1500} value={query} onChange={e=>setQuery(e.target.value)} placeholder={kind==="discover"?"study tips, exam routine, study motivation":"@compte, @concurrent"}/></label>
      <button className="ss-btn-purple" disabled={busy||source==="provider"&&!available}>{busy?tr("Démarrage…","Starting…"):tr("Lancer la recherche","Start research")}</button></div>
      <details className="ss-research-options"><summary>{tr("Critères et profondeur de recherche","Research filters and depth")}</summary><div className="ss-research__form">
      <label>{tr("Source","Source")}<select className="ss-input" value={source} onChange={e=>setSource(e.target.value)}><option value="provider" disabled={!available}>{tr("Collecte cloud","Cloud collection")}</option><option value="browser">{tr("Mon navigateur connecté","My connected browser")}</option></select></label>
      {[{label:tr("Période (jours)","Period (days)"),value:days,set:setDays,min:1,max:365},{label:tr("Comptes recherchés","Target accounts"),value:target,set:setTarget,min:1,max:50},{label:tr("Carrousels minimum (%)","Minimum photos (%)"),value:minShare,set:setMinShare,min:0,max:100},{label:tr("Vues cumulées minimum","Minimum total views"),value:minViews,set:setMinViews,min:0,max:1e12},{label:tr("Vues médianes minimum","Minimum median views"),value:minMedian,set:setMinMedian,min:0,max:1e10},{label:tr("Carrousels mesurés minimum","Minimum measured photos"),value:minPosts,set:setMinPosts,min:1,max:100},{label:tr("Pages maximum par compte","Maximum pages per account"),value:maxPages,set:setMaxPages,min:1,max:10}].map(f=><label key={f.label}>{f.label}<input className="ss-input" type="number" required min={f.min} max={f.max} value={f.value} onChange={e=>f.set(Number(e.target.value))}/></label>)}
      <label className="ss-research-check"><input type="checkbox" checked={pivot} onChange={e=>setPivot(e.target.checked)}/>{tr("Explorer les hashtags trouvés","Explore discovered hashtags")}</label></div></details>
    </form>
    {source==="browser"&&<p className="ss-lead">{tr("Le collecteur local doit être lancé sur ton Mac. Ta session TikTok reste dans son profil Chrome dédié. Aucun like ni publication automatique.","Run the local collector on your Mac. Your TikTok session stays in its dedicated Chrome profile. No automatic likes or publishing.")} <a href="/research-collector.md" target="_blank">{tr("Configurer le collecteur","Set up collector")}</a></p>}
    {!available&&source==="provider"&&<p role="status">{tr("Le service cloud n’est pas configuré. Utilise ton collecteur navigateur ou connecte le service dans l’environnement serveur.","Cloud collection is not configured. Use the browser collector or configure the server service.")}</p>}
    <p className="ss-research-footnote">{tr("Les vues sont les compteurs des carrousels publiés pendant la période. Les résultats indiquent leur couverture et leur date ; une moyenne élevée ne suffit pas à prouver un format gagnant.","Views are lifetime counters on photo posts published in the period. Results include coverage and date; a high average alone does not prove a winning format.")}</p></section>
    {error&&<div className="ss-panel" role="alert">{tr("L’opération n’a pas abouti : ","The operation failed: ")}{error}<button className="ss-btn-ghost" onClick={()=>setError("")}>{tr("Fermer","Dismiss")}</button></div>}
    <nav className="ss-research-tabs lg lg--flat" aria-label={tr("Vues de recherche","Research views")}>{[["library",tr("Comptes","Accounts"),items.length],["runs",tr("Recherches","Research jobs"),jobs.length],["formats",tr("Formats étudiés","Studied formats"),studies.length]].map(([id,label,n])=><button key={id} className={tab===id?"ss-btn-purple":"ss-btn-ghost"} onClick={()=>setTab(String(id))} aria-pressed={tab===id}>{label} <span>{n}</span></button>)}</nav>
    {loading&&<p role="status">{tr("Chargement…","Loading…")}</p>}
    {tab==="library"&&<><div className="ss-research__form"><label>{tr("Filtrer les comptes","Filter accounts")}<input className="ss-input" value={filter} onChange={e=>setFilter(e.target.value)} placeholder={tr("Compte ou niche","Account or niche")}/></label><label>{tr("Classer par","Sort by")}<select className="ss-input" value={sort} onChange={e=>setSort(e.target.value)}><option value="median">{tr("Vues médianes","Median views")}</option><option value="ratio">{tr("Vues / abonné","Views / follower")}</option><option value="followers">{tr("Abonnés","Followers")}</option></select></label><a className="ss-btn-ghost" href="/app/mcp">{tr("Construire ma stratégie avec mon assistant","Build my strategy with my assistant")}</a></div>
    {!loading&&!visible.length&&<section className="ss-panel"><h3>{tr("Tes premiers formats commencent par une recherche","Your first formats start with research")}</h3><p>{tr("Indique ta niche ou un compte ci-dessus. Les mesures, publications et études seront réunies ici.","Enter a niche or account above. Measurements, posts and studies will appear here.")}</p></section>}
    <div className="ss-research__grid">{visible.map(({account:a,metrics:m,measuredAt})=><article className="ss-panel" key={a.id}><h3><a href={`https://www.tiktok.com/@${a.handle}`} target="_blank" rel="noreferrer">@{a.handle}</a></h3><p className="ss-lead">{a.niche||a.bio}</p><dl className="ss-research__metrics">{[[tr("Abonnés","Followers"),num(a.followers)],[tr("Vues médianes","Median views"),num(m.medianViews)],[tr("Carrousels","Photos"),percent(m.slideshowShare)],[tr("Photos mesurées","Measured photos"),num(m.measuredSlideshowPosts)],[tr("Enregistrements / vues","Saves / views"),percent(m.saveRate)],[tr("Poids du meilleur post","Top post share"),percent(m.topPostShare)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="ss-research-footnote">{measuredAt?new Date(measuredAt).toLocaleString():tr("Non mesuré","Not measured")} · {a.researchCoverage?.complete&&a.researchCoverage.windowDays>=days?tr("Période couverte","Period covered"):tr("Échantillon partiel","Partial sample")}</p>
    {(m.confidence==="insufficient_data"||m.repeatability==="single_post_dominated")&&<p className="ss-research-signal">{m.confidence==="insufficient_data"?tr("Trop peu de carrousels pour conclure.","Too few carousels to draw conclusions."):tr("La majorité des vues provient d’un seul post.","Most views come from one post.")}</p>}
    <details><summary>{tr("Carrousels à étudier","Carousels to study")} ({m.topPosts.length})</summary><div className="ss-research-posts">{m.topPosts.map(p=><div className="ss-research-post" key={p.id}>{p.cover&&<img src={`/api/studio/tiktok/cover?url=${encodeURIComponent(p.cover)}`} alt="" loading="lazy"/>}<div><a href={p.url} target="_blank" rel="noreferrer">{p.title||p.id}</a><small>{num(p.views)} {tr("vues","views")} · {p.images?.length??"—"} slides</small><button className="ss-btn-ghost" disabled={studying||!p.images?.length} onClick={()=>void openStudy(a.id,p.id)}>{studying?tr("Lecture…","Reading…"):tr("Étudier le format","Study format")}</button></div></div>)}</div></details></article>)}</div></>}
    {tab==="runs"&&<div className="ss-research-run-layout"><div className="ss-research-run-list">{!jobs.length&&<p>{tr("Aucune recherche lancée.","No research jobs yet.")}</p>}{jobs.map(j=><button key={j.id} className={`ss-panel ss-research-run ${selectedJob===j.id?"is-selected":""}`} onClick={()=>setSelectedJob(j.id)}><strong>{j.input.keywords.slice(0,3).join(", ")}</strong><span>{status(j.status)}</span><small>{j.progress.accepted}/{j.progress.target} {tr("retenus","selected")} · {j.progress.measured} {tr("mesurés","measured")}</small></button>)}</div>{selected&&<section className="ss-panel"><h3>{selected.input.keywords.join(", ")}</h3><p role="status">{status(selected.status)} · {selected.progress.candidates} {tr("candidats","candidates")} · {selected.progress.measured} {tr("comptes mesurés","measured accounts")}</p><progress max={Math.max(selected.progress.target,selected.progress.accepted)} value={selected.progress.accepted}/><div className="ss-research-actions">{["running","queued"].includes(selected.status)&&<button className="ss-btn-ghost" onClick={()=>void control(selected.id,"pause")}>{tr("Pause","Pause")}</button>}{["paused","needs_attention"].includes(selected.status)&&<button className="ss-btn-purple" onClick={()=>void control(selected.id,"resume")}>{tr("Reprendre","Resume")}</button>}{!["done","stopped"].includes(selected.status)&&<button className="ss-btn-ghost" onClick={()=>void control(selected.id,"stop")}>{tr("Arrêter","Stop")}</button>}{selected.status!=="stopped"&&<button className="ss-btn-ghost" onClick={()=>void control(selected.id,"resume",true)}>{tr("Appliquer les critères du formulaire","Apply form filters")}</button>}</div>
    {selected.input.source==="browser"&&<p>{tr("Identifiant à transmettre au collecteur : ","Collector job ID: ")}<code>{selected.id}</code></p>}{selected.error&&<p role="alert">{selected.error}</p>}{selected.status==="done"&&selected.progress.accepted<selected.progress.target&&<p>{tr("Recherche terminée avec moins de comptes que demandé. Examine les motifs de rejet ou élargis tes mots-clés.","Research finished below the target. Review rejection reasons or broaden keywords.")}</p>}
    <div className="ss-research-table-wrap"><table className="ss-research-table"><thead><tr><th>{tr("Compte","Account")}</th><th>{tr("Médiane","Median")}</th><th>{tr("Photos","Photos")}</th><th>{tr("Résultat","Result")}</th></tr></thead><tbody>{selected.results.map(r=><tr key={r.handle}><td><a href={`https://www.tiktok.com/@${r.handle}`} target="_blank" rel="noreferrer">@{r.handle}</a><small>{r.coverage.complete?tr("Couvert","Covered"):tr("Partiel","Partial")}</small></td><td>{num(r.metrics.medianViews)}</td><td>{r.metrics.measuredSlideshowPosts}</td><td>{r.accepted?tr("Retenu","Selected"):r.reasons.map(reason).join(" · ")}</td></tr>)}</tbody></table></div>{!!selected.failures.length&&<details><summary>{tr("Erreurs conservées","Saved errors")}</summary>{selected.failures.map((f,i)=><p key={i}>{f.handle||f.keyword} : {f.error}</p>)}</details>}</section>}</div>}
    {tab==="formats"&&<>{!studies.length&&!study&&<section className="ss-panel"><h3>{tr("Lis un format, pas seulement ses chiffres","Read a format, beyond its numbers")}</h3><p>{tr("Dans Comptes, ouvre les carrousels d’un profil puis choisis Étudier le format. L’étude conserve chaque slide et son texte ; ton assistant peut ajouter son interprétation sourcée.","Under Accounts, open a profile’s carousels and choose Study format. The study keeps every slide and its text; your assistant can add an evidence-backed interpretation.")}</p></section>}
    {!!studies.length&&<div className="ss-research-study-list">{studies.map(s=><button className="ss-btn-ghost" key={s.id} onClick={()=>{void api(`/api/research/studies/${s.id}`).then(setStudy).catch(e=>setError(e.message));}}>{s.interpretation?.name||s.caption.slice(0,65)||s.postId} · {s.slides.length} slides</button>)}</div>}
    {study&&<section className="ss-panel"><div className="ss-research-study-head"><div><h3>{study.interpretation?.name||tr("Étude du carrousel","Carousel study")}</h3><a href={study.sourceUrl} target="_blank" rel="noreferrer">{tr("Publication d’origine","Original post")}</a><p>{num(study.post?.views)} {tr("vues","views")} · {tr("Médiane du compte : ","Account median: ")}{num(study.baseline.medianViews)}{study.lift!==null?` · ×${study.lift.toFixed(1)}`:""}</p></div><div className="ss-research-actions"><a className="ss-btn-ghost" href={`/api/research/studies/${study.id}/export`}>{tr("Télécharger l’étude ZIP","Download ZIP study")}</a>{study.status==="pending"&&<button className="ss-btn-purple" disabled={studying} onClick={()=>void continueStudy()}>{studying?tr("Lecture…","Reading…"):tr("Lire les slides suivantes","Read remaining slides")}</button>}</div></div>
    <div className="ss-research-slides">{study.slides.map(s=><article key={s.index}><img src={`/api/studio/tiktok/cover?url=${encodeURIComponent(s.image)}`} alt={`Slide ${s.index}`} loading="lazy"/><strong>Slide {s.index}</strong><small>{s.status==="pending"?tr("À lire","Pending"):s.status==="unreadable"?tr("Transcription incertaine — inspecter le visuel","Uncertain transcript — inspect image"):`OCR ${num(s.confidence)} %`}</small><p>{s.text}</p></article>)}</div>
    {study.interpretation?<div className="ss-research-interpretation"><h4>{tr("Interprétation de l’assistant","Assistant interpretation")}</h4>{[[tr("Accroche","Hook"),study.interpretation.hook],[tr("Narration","Narrative"),study.interpretation.narrative],[tr("Motif visuel","Visual pattern"),study.interpretation.visualPattern],[tr("Émotion et audience","Emotion and audience"),`${study.interpretation.emotionalAngle} — ${study.interpretation.audience}`],[tr("Appel à l’action","Call to action"),study.interpretation.cta],[tr("Adaptation à ton activité","Business adaptation"),study.interpretation.adaptation],[tr("Hypothèse à tester","Hypothesis to test"),study.interpretation.hypothesis]].map(([label,text])=><div key={label}><strong>{label}</strong><p>{text}</p></div>)}<p>{tr("Slides citées : ","Cited slides: ")}{study.interpretation.evidenceSlides.join(", ")}</p></div>:<p className="ss-lead">{tr("Les preuves sont prêtes pour ton assistant. Demande-lui d’analyser cette étude et de sauvegarder le format avec ses sources. Le texte OCR seul ne décrit pas toute l’image.","Evidence is available to your assistant. Ask it to analyze this study and save the format with its sources. OCR alone cannot describe the entire image.")} <a href="/app/mcp">{tr("Connecter mon assistant","Connect my assistant")}</a></p>}</section>}</>}
  </div>;
}
