"use client";

import { useEffect, useLayoutEffect, useRef, useState } from "react";

export function TikTokSlides({ images, en, onOpen, onSlideChange, large = false, initialIndex = 0 }: {
  images: string[];
  en: boolean;
  onOpen?: (index: number) => void;
  onSlideChange?: (index: number) => void;
  initialIndex?: number;
  large?: boolean;
}) {
  const track = useRef<HTMLDivElement>(null);
  const [index, setIndex] = useState(Math.min(initialIndex, images.length - 1));
  const drag = useRef<{ x: number; scroll: number; moved: boolean } | null>(null);
  const [failed, setFailed] = useState<Record<number, boolean>>({});
  useEffect(() => { onSlideChange?.(index); }, [index, onSlideChange]);
  useLayoutEffect(() => {
    if (track.current) track.current.scrollLeft = initialIndex * track.current.clientWidth;
  }, [initialIndex]);
  const move = (next: number) => {
    const at = Math.max(0, Math.min(images.length - 1, next));
    setIndex(at);
    track.current?.scrollTo({ left: at * track.current.clientWidth, behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth" });
  };
  return <div className={`ss-slides ${large ? "ss-slides--large" : ""}`}>
    <div ref={track} className="ss-slides__track" role="region" aria-roledescription={en ? "carousel" : "carrousel"}
      aria-label={en ? "Post slides" : "Slides de la publication"} tabIndex={0}
      onScroll={() => { if (track.current?.clientWidth) setIndex(Math.round(track.current.scrollLeft / track.current.clientWidth)); }}
      onKeyDown={e => {
        if (e.key === "ArrowRight" || e.key === "ArrowLeft") { e.preventDefault(); move(index + (e.key === "ArrowRight" ? 1 : -1)); }
        if (e.key === "Home" || e.key === "End") { e.preventDefault(); move(e.key === "Home" ? 0 : images.length - 1); }
      }}
      onPointerDown={e => { drag.current = null; if (e.pointerType === "mouse" && e.button === 0 && track.current) drag.current = { x: e.clientX, scroll: track.current.scrollLeft, moved: false }; }}
      onPointerMove={e => {
        const d = drag.current;
        if (!d || !e.buttons || !track.current) return;
        if (Math.abs(e.clientX - d.x) > 8) {
          d.moved = true;
          track.current.setPointerCapture(e.pointerId);
          track.current.scrollLeft = d.scroll - (e.clientX - d.x);
        }
      }}
      onPointerUp={e => {
        if (drag.current?.moved && track.current) {
          if (track.current.hasPointerCapture(e.pointerId)) track.current.releasePointerCapture(e.pointerId);
          move(Math.round(track.current.scrollLeft / track.current.clientWidth));
        }
        // Retain the moved flag through the click generated by pointerup.
      }}
      onPointerCancel={() => { drag.current = null; }}>
      {images.map((url, i) => <div className="ss-slides__slide" key={`${i}:${url}`} role="group" aria-label={`${i + 1} / ${images.length}`}>
        <button type="button" className="ss-slides__image" aria-disabled={!onOpen} tabIndex={onOpen && i === index ? 0 : -1}
          aria-label={en ? `Open slide ${i + 1}` : `Agrandir la slide ${i + 1}`}
          onClick={() => { if (!drag.current?.moved) onOpen?.(i); drag.current = null; }}>
          {failed[i] ? <span className="ss-slides__unavailable">{en ? "Image unavailable · refresh the account" : "Image indisponible · actualise le compte"}</span> : Math.abs(i - index) <= 1 ?
            <img src={url.startsWith("/") ? url : `/api/studio/tiktok/cover?url=${encodeURIComponent(url)}`} alt={en ? `Slide ${i + 1} of ${images.length}` : `Slide ${i + 1} sur ${images.length}`} draggable={false} loading="lazy" onError={() => setFailed(prev => ({ ...prev, [i]: true }))} /> : null}
        </button>
      </div>)}
    </div>
    {images.length > 1 ? <div className="ss-slides__controls lg">
      <button type="button" className="lg-press" aria-label={en ? "Previous slide" : "Slide précédente"} disabled={index === 0} onClick={() => move(index - 1)}>‹</button>
      <span aria-live="polite" aria-atomic="true">{index + 1} / {images.length}</span>
      <button type="button" className="lg-press" aria-label={en ? "Next slide" : "Slide suivante"} disabled={index === images.length - 1} onClick={() => move(index + 1)}>›</button>
    </div> : null}
  </div>;
}
