import assert from "node:assert/strict";
import * as repo from "../../lib/business-analytics/repository";
import { processShopifyPrivacy, listShopifyPrivacyRequests, exportShopifyPrivacyRequest } from "../../lib/business-analytics/shopify-privacy";
import { shopifyPrivacyFenceId } from "../../lib/business-analytics/shopify-privacy-rules";
import { setBusinessConnectionMonetarySource } from "../../lib/business-analytics/connections";

export async function exerciseShopifyPrivacy(suffix="local") {
  const scope={userId:`privacy-owner-${suffix}`,projectId:"privacy-project"},other={...scope,projectId:"privacy-other"},shop=`privacy-test-${suffix}.myshopify.com`;
  const connection=await repo.saveConnection(scope,{provider:"shopify",name:"Shop",externalAccountId:"123",environment:"live",status:"connected",monetarySource:false,encryptedCredentials:"encrypted-test-credential",metadata:{shopDomain:shop,shopifyAuthorizedAt:"2026-01-01T00:00:00Z"}});
  const foreign=await repo.saveConnection(other,{provider:"shopify",name:"Other",externalAccountId:"456",environment:"live",status:"connected",metadata:{shopDomain:"other-test.myshopify.com",shopifyAuthorizedAt:"2026-01-01T00:00:00Z"}});
  const sale={provider:"shopify" as const,connectionId:connection.id,externalAccountId:"123",environment:"live" as const,externalId:"order:10:transaction:20",customerId:"100",status:"paid" as const,kind:"one_time" as const,amountMinor:1000,taxMinor:100,feeMinor:0,currency:"EUR",occurredAt:"2026-06-01T00:00:00Z",source:"provider" as const,clickId:"privacy-click"};
  await repo.saveClick(scope,{id:"privacy-click",linkId:"privacy-link",visitorId:"privacy-visitor",occurredAt:"2026-05-31T00:00:00Z",source:"landing"});
  const payment=await repo.saveTransaction(scope,sale);
  await repo.saveAdjustment(scope,{transactionId:payment.id,connectionId:connection.id,provider:"shopify",externalId:"refund20",kind:"refund",amountMinor:100,taxMinor:10,currency:"EUR",occurredAt:"2026-06-02T00:00:00Z",source:"provider"});
  await repo.saveTransaction(scope,{...sale,externalId:"order:11:transaction:21",customerId:"101",clickId:undefined});
  await repo.saveTransaction(other,{...sale,connectionId:foreign.id,externalAccountId:"456",clickId:undefined});
  await repo.saveTransaction(scope,{...sale,provider:"stripe",externalAccountId:"acct_keep",connectionId:undefined,externalId:"ch_keep",clickId:undefined});
  await repo.saveIdentity(scope,{provider:"shopify",externalAccountId:"123",environment:"live",externalId:"customer-link",customerId:"100",visitorId:"privacy-visitor",clickId:"privacy-click",firstSeenAt:"2026-05-31T00:00:00Z"});
  await repo.saveEvent(scope,{externalId:"signup100",provider:"shopify:123:live",customerId:"100",visitorId:"privacy-visitor",clickId:"privacy-click",kind:"signup",source:"server",occurredAt:"2026-05-31T00:00:00Z"});
  const payload={shop_id:123,shop_domain:shop,customer:{id:100,email:"not-stored@example.com",phone:"not-stored"},orders_requested:[10],data_request:{id:900}};
  await processShopifyPrivacy(shop,"customers/data_request",payload,"hook1");
  await assert.rejects(processShopifyPrivacy(shop,"shop/redact",payload,"replayed-topic",new Date().toISOString()),/shopify_privacy_payload_invalid/);
  await processShopifyPrivacy(shop,"customers/data_request",payload,"hook1");
  const requests=await listShopifyPrivacyRequests(scope);assert.equal(requests.pending,1);assert.equal(requests.requests.length,1);assert.equal(requests.requests[0].shopId,"123");
  assert.equal((await listShopifyPrivacyRequests(other)).pending,0);
  await assert.rejects(exportShopifyPrivacyRequest(other,requests.requests[0].id),/not_found/);
  const bundle=await exportShopifyPrivacyRequest(scope,requests.requests[0].id);
  assert.equal(bundle.transactions.length,1);assert.equal(bundle.adjustments.length,1);assert.equal(bundle.identities.length,1);assert.equal(bundle.events.length,1);assert.equal(bundle.clicks.length,1);
  assert.equal(JSON.stringify(bundle).includes("encrypted-test-credential"),false);assert.equal(JSON.stringify(bundle).includes("not-stored@example.com"),false);assert.equal((await listShopifyPrivacyRequests(scope)).pending,0);
  await Promise.allSettled([repo.saveTransaction(scope,{...sale,externalId:"order:12:transaction:22"}),processShopifyPrivacy(shop,"customers/redact",{shop_id:123,shop_domain:shop,customer:{id:100},orders_to_redact:[10]},"redact1")]);
  const after=await repo.readProject(scope);
  assert.equal(after.transactions.some(t=>t.provider==="shopify"&&t.customerId==="100"),false);assert.equal(after.adjustments.length,0);assert.equal(after.events.length,0);assert.equal(after.clicks.length,0);
  assert.equal(after.transactions.filter(t=>t.provider==="stripe").length,1);assert.equal((await repo.listTransactions(other)).length,1);
  assert.ok(await repo.getRecord(scope,"identities",shopifyPrivacyFenceId("customer","123","100")));
  await processShopifyPrivacy(shop,"customers/data_request",payload,"hook1");
  assert.equal((await listShopifyPrivacyRequests(scope)).requests.length,0,"redacted access request cannot be resurrected by a webhook retry");
  await assert.rejects(repo.saveTransaction(scope,sale),/shopify_data_redacted/);
  await assert.rejects(repo.saveTransaction(scope,{...sale,customerId:undefined}),/shopify_data_redacted/);
  await assert.rejects(repo.saveClick(scope,{id:"privacy-click",linkId:"privacy-link",visitorId:"privacy-visitor",occurredAt:"2026-05-31T00:00:00Z",source:"landing"}),/shopify_data_redacted/);
  const redactedAt=new Date().toISOString();
  await processShopifyPrivacy(shop,"shop/redact",{shop_id:123,shop_domain:shop},"shop-redact",redactedAt);
  await processShopifyPrivacy(shop,"shop/redact",{shop_id:123,shop_domain:shop},"shop-redact",redactedAt);
  assert.equal((await repo.listConnections(scope)).length,0);assert.equal((await repo.listTransactions(scope)).length,1);assert.equal((await repo.listTransactions(scope))[0].provider,"stripe");
  await assert.rejects(repo.saveConnection(scope,connection),/shopify_data_redacted/);
  const newAuthorization=new Date(Date.now()+1000).toISOString();
  const reconnected=await repo.saveConnection(scope,{...connection,metadata:{...connection.metadata,shopifyAuthorizedAt:newAuthorization}});
  await processShopifyPrivacy(shop,"shop/redact",{shop_id:123,shop_domain:shop},"shop-redact",redactedAt);
  assert.equal((await repo.listConnections(scope)).length,1);
  await assert.rejects(repo.saveTransaction(scope,{...sale,connectionId:reconnected.id,customerId:"102",externalId:"order:99:transaction:99"}),/shopify_data_redacted/);
  const fresh=await repo.saveTransaction(scope,{...sale,connectionId:reconnected.id,customerId:"102",externalId:"order:99:transaction:99",clickId:undefined,occurredAt:newAuthorization});assert.equal(fresh.customerId,"102");
  // Structurally wider scopes may never overwrite payload values or leak connection credentials into a payment.
  const extraScope={...scope,encryptedCredentials:"secret-never-copied",name:"old",status:"disconnected"};
  const safe=await repo.saveTransaction(extraScope,{...sale,provider:"stripe",connectionId:undefined,externalAccountId:"acct_extra",externalId:"ch_safe",customerId:undefined,clickId:undefined});
  assert.equal("encryptedCredentials" in safe,false);assert.equal(safe.status,"paid");
  const stripe=await repo.saveConnection(scope,{provider:"stripe",externalAccountId:"acct_keep",name:"Stripe",environment:"live",status:"connected",monetarySource:false});
  const switched=await Promise.allSettled([setBusinessConnectionMonetarySource(scope,reconnected.id,true),setBusinessConnectionMonetarySource(scope,stripe.id,true)]);
  assert.equal(switched.filter(row=>row.status==="fulfilled").length,1,"concurrent source changes permit only one overlapping monetary source");
  assert.equal(switched.filter(row=>row.status==="rejected"&&String(row.reason).includes("stripe_shopify_overlap")).length,1);
  const active=(await repo.listConnections(scope)).find(row=>row.monetarySource!==false)!;
  await setBusinessConnectionMonetarySource(scope,active.id,false);
  const target=active.id===stripe.id?reconnected.id:stripe.id;
  await setBusinessConnectionMonetarySource(scope,target,true);
  assert.equal((await repo.listConnections(scope)).filter(row=>row.monetarySource!==false).length,1);
  assert.equal((await repo.listTransactions(scope)).length,3,"source changes retain historical payments");
}
